---
name: my-postgres
director_uuid: <%= `bosh target > /dev/null 2>&1 && bosh status --uuid` %> # CHANGE ME

releases:
- name: my-postgres
  version: latest


networks:
- name: default
  subnets:
  - range: 10.244.15.0/24 # CHANGE ME
    reserved: 10.244.15.1 # CHANGE ME
    static: 10.244.15.2 - 10.244.15.20 # CHANGE ME
    cloud_properties:
      name: default # CHANGE ME

resource_pools:
- name: default
  stemcell:
    name:  bosh-warden-boshlite-centos-7-go_agent
    version: latest
  network: default
  cloud_properties:
    ram: 4096
    disk: 8192
    cpu: 2
    datacenters:
    - clusters:
      - CLUSTER-NAME: {} # CHANGE ME

compilation:
  workers: 1
  cloud_properties:
    ram: 8192
    disk: 8096
    cpu: 4
    datacenters:
    - clusters:
      - CLUSTER-NAME: {} # CHANGE ME
  network: default
  reuse_compilation_vms: true


update:
  canaries: 1
  canary_watch_time: 3000 - 180000
  update_watch_time: 3000 - 180000
  max_in_flight: 2
  max_errors: 1


jobs:
 - name: my-pg-server
   template: my-pg-server
   instances: 1
   resource_pool: default
   persistent_disk: 7128
   properties:
     host: 10.244.15.3 # CHANGE ME
   networks:
   - name: default
     static_ips:
     - 10.244.15.3 # CHANGE ME
